### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mwv** [bootphon/features_extraction#1]
There is an issue with the licensing on this repo. The included packages amtoolbox, ltfat and rastamat are all GPL (not sure about AuditoryToolbox). The code that I wrote is the same. Yet the license in the top-level of this repo is MIT, which is not compatible, and somehow assigns copyright to Thomas. 

Can the top-level license be changed to GPL and assign copyright appropriately?

**Comment by mmmaat** [comment]
As of commit a1503e8ab61b4c72366e59b3165d71b8975812ac license is GPLv3.
